<?xml version="1.0" encoding="utf-8"?>
<nitro_policy esm="B5BF:C090" time="09/17/2019 20:55:44" user="NGCP" build="11.2.1 20190725050014" model="ETM-VM8" version="11002001">
  <rules count="57">
    <rule>
      <id>47-6000003</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Empire PowerShell Launch Parameters</message>
      <description>Detects suspicious powershell command line parameters used in Empire
https://github.com/EmpireProject/Empire/blob/c2ba61ca8d2031dad0cfc1d5770ba723e8b710db/lib/common/helpers.py#L165
https://github.com/EmpireProject/Empire/blob/e37fb2eef8ff8f5a0a689f1589f424906fe13055/lib/modules/powershell/persistence/powerbreach/deaduser.py#L191
https://github.com/EmpireProject/Empire/blob/e37fb2eef8ff8f5a0a689f1589f424906fe13055/lib/modules/powershell/persistence/powerbreach/resolver.py#L178
https://github.com/EmpireProject/Empire/blob/e37fb2eef8ff8f5a0a689f1589f424906fe13055/data/module_source/privesc/Invoke-EventVwrBypass.ps1#L64</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000003" name="Process Creation - Empire PowerShell Launch Parameters" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[-NoP%20-NonI%20-W%20Hidden%20-enc,-NoP%20-sta%20-NonI%20-W%20Hidden%20-Enc,-noP%20-sta%20-w%201%20-enc]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000003</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:t1086</tag>
    </rule>
    <rule>
      <id>47-6000004</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Windows Kernel and 3rd-party drivers exploits Token stealing</message>
      <description>Detection of child processes spawned with SYSTEM privileges by parents with non-SYSTEM privileges and Medium integrity level
https://www.slideshare.net/heirhabarov/hunting-for-privilege-escalation-in-windows-environment</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000004" name="Process Creation - Windows Kernel and 3rd-party drivers exploits Token stealing" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388609">
        <filterData name="value" value="User|6751494449278544611[SYSTEM]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388611">
        <filterData name="value" value="IntegrityLevel|6751494449278544611[Medium]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000004</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:privilege_escalation</tag>
      <tag origin="1">attack:t1068</tag>
    </rule>
    <rule>
      <id>47-6000005</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Suspicious Double Extension</message>
      <description>Detects suspicious use of an .exe extension after a non-executable file extension like .pdf.exe, a set of spaces or underlines to cloak the executable file in spear phishing campaigns
https://blu3-team.blogspot.com/2019/06/misleading-extensions-xlsexe-docexe.html
https://twitter.com/blackorbird/status/1140519090961825792</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000005" name="Process Creation - Suspicious Double Extension" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454178">
        <filterData name="value" value="Image|12622590293378144023[(%3Fi)%5C.(docx%3F%7Cxlsx%3F%7Cpptx%3F%7Crtf%7Cpdf%7Ctxt%7C%5Cs%7B5%2C%7D%7C_%7B5%2C%7D)%5C.exe]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000005</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:t1193</tag>
      <tag origin="1">attack:initial_access</tag>
    </rule>
    <rule>
      <id>47-6000006</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - WannaCry Ransomware</message>
      <description>Detects WannaCry ransomware activity
https://www.hybrid-analysis.com/sample/ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa?environmentId=100</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000006" name="Process Creation - WannaCry Ransomware" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="trigger_1" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" ordinal="1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454178">
        <filterData name="value" value="Image|12622590293378144023[111.exe,diskpart.exe,lhdfrgui.exe,linuxnew.exe,mssecsvc.exe,taskdl.exe,taskhsvc,tasksche.exe,taskse.exe,WanaDecryptor,wannacry.exe]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="rule_2" ordinal="2" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)%40Please_Read_Me%40%5C.txt,(%3Fi)bcdedit%20%2Fset%20%7Bdefault%7D%20recoveryenabled%20no,(%3Fi)icacls.*%2Fgrant%20Everyone%3AF%20%2FT%20%2FC%20%2FQ,(%3Fi)wbadmin%20delete%20catalog%20-quiet]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="rule_3" ordinal="3" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454179">
        <filterData name="value" value="ParentCommandLine|12622590293378144023[(%3Fi)%40Please_Read_Me%40%5C.txt,(%3Fi)bcdedit%20%2Fset%20%7Bdefault%7D%20recoveryenabled%20no,(%3Fi)icacls.*%2Fgrant%20Everyone%3AF%20%2FT%20%2FC%20%2FQ,(%3Fi)wbadmin%20delete%20catalog%20-quiet]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="rule_4" ordinal="4" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454177">
        <filterData name="value" value="ParentImage|12622590293378144023[111.exe,diskpart.exe,lhdfrgui.exe,linuxnew.exe,mssecsvc.exe,taskdl.exe,taskhsvc.exe,tasksche.exe,taskse.exe,WanaDecryptor,wannacry.exe]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="trigger_1"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000006</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
    </rule>
    <rule>
      <id>47-6000007</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Ransomware Deletes Volume Shadow Copies</message>
      <description>Detects commands that delete all local volume shadow copies as used by different Ransomware families
https://www.bleepingcomputer.com/news/security/why-everyone-should-disable-vssadmin-exe-now/
https://www.hybrid-analysis.com/sample/ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa?environmentId=100</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000007" name="Process Creation - Ransomware Deletes Volume Shadow Copies" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)vsasdmin%20delete%20shadows,(%3Fi)wmic%20SHADOWCOPY%20DELETE]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000007</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
    </rule>
    <rule>
      <id>47-6000008</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Exploit for CVE-2017-8759</message>
      <description>Detects Winword starting uncommon sub process csc.exe as used in exploits for CVE-2017-8759
https://www.hybrid-analysis.com/sample/0b4ef455e385b750d9f90749f1467eaf00e46e8d6c2885c260e1b78211a51684?environmentId=100
https://www.reverse.it/sample/0b4ef455e385b750d9f90749f1467eaf00e46e8d6c2885c260e1b78211a51684?environmentId=100</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000008" name="Process Creation - Exploit for CVE-2017-8759" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388616">
        <filterData name="value" value="ParentName|6751494449278544611[WINWORD.EXE]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[csc.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000008</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:t1203</tag>
    </rule>
    <rule>
      <id>47-6000010</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Exploit for CVE-2015-1641</message>
      <description>Detects Winword starting uncommon sub process MicroScMgmt.exe as used in exploits for CVE-2015-1641
https://www.virustotal.com/en/file/5567408950b744c4e846ba8ae726883cb15268a539f3bb21758a466e47021ae8/analysis/
https://www.hybrid-analysis.com/sample/5567408950b744c4e846ba8ae726883cb15268a539f3bb21758a466e47021ae8?environmentId=100</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000010" name="Process Creation - Exploit for CVE-2015-1641" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388616">
        <filterData name="value" value="ParentName|6751494449278544611[WINWORD.EXE]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[MicroScMgmt.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000010</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:t1036</tag>
    </rule>
    <rule>
      <id>47-6000012</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Cmdkey Cached Credentials Recon</message>
      <description>Detects usage of cmdkey to look for cached credentials
https://www.peew.pw/blog/2017/11/26/exploring-cmdkey-an-edge-case-for-privilege-escalation
https://technet.microsoft.com/en-us/library/cc754243(v=ws.11).aspx</description>
      <origin>1</origin>
      <severity>25</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000012" name="Process Creation - Cmdkey Cached Credentials Recon" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[cmdkey.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)%2Flist]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000012</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:t1003</tag>
      <tag origin="1">attack:credential_access</tag>
    </rule>
    <rule>
      <id>47-6000013</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Hiding files with attrib</message>
      <description>Detects usage of attrib.exe to hide files from users.</description>
      <origin>1</origin>
      <severity>25</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000013" name="Process Creation - Hiding files with attrib" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[attrib.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[%2Bh]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388616">
        <filterData name="value" value="ParentName|6751494449278544611[cmd.exe]"/>
        <filterData name="operator" value="DOES_NOT_EQUAL"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000013</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:persistence</tag>
      <tag origin="1">attack:t1158</tag>
    </rule>
    <rule>
      <id>47-6000014</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - CMSTP UAC Bypass via COM Object Access</message>
      <description>Detects UAC Bypass Attempt Using Microsoft Connection Manager Profile Installer Autoelevate-capable COM Objects
http://www.endurant.io/cmstp/detecting-cmstp-enabled-code-execution-and-uac-bypass-with-sysmon/
https://twitter.com/hFireF0X/status/897640081053364225</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000014" name="Process Creation - CMSTP UAC Bypass via COM Object Access" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388616">
        <filterData name="value" value="ParentName|6751494449278544611[dllhost.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[%7B3E000D72-A845-4CD9-BD83-80C07C3B881F%7D,%7B3E5FC7F9-9A51-4367-9063-A120244FBEC7%7D]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000014</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:privilege_escalation</tag>
      <tag origin="1">attack:t1088</tag>
      <tag origin="1">attack:t1191</tag>
      <tag origin="1">attack:g0069</tag>
      <tag origin="1">car:2019-04-001</tag>
    </rule>
    <rule>
      <id>47-6000015</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Encoded FromBase64String</message>
      <description>Detects a FromBase64String keyword in a process command line</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000015" name="Process Creation - Encoded FromBase64String" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="trigger_1" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" ordinal="1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[%3A%3AFromBase64String]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="rule_2" ordinal="2" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454179">
        <filterData name="value" value="ParentCommandLine|12622590293378144023[%3A%3AFromBase64String]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="trigger_1"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000015</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:t1086</tag>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:t1140</tag>
    </rule>
    <rule>
      <id>47-6000016</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Disable of ETW Trace</message>
      <description>Detects a command that clears or disables any ETW trace log which could indicate a logging evasion.
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wevtutil
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wevtutil
https://abuse.io/lockergoga.txt</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000016" name="Process Creation - Disable of ETW Trace" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)cl%20.*%2FTrace,(%3Fi)clear-log%20.*%2FTrace,(%3Fi)set-log.*%20%2Fe%3Afalse,(%3Fi)sl.*%20%2Fe%3Afalse]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000016</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:t1070</tag>
      <tag origin="1">car:2016-04-002</tag>
    </rule>
    <rule>
      <id>47-6000018</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - MavInject Process Injection</message>
      <description>Detects process injection using the signed Windows tool Mavinject32.exe
https://twitter.com/gN3mes1s/status/941315826107510784
https://reaqta.com/2017/12/mavinject-microsoft-injector/
https://twitter.com/Hexacorn/status/776122138063409152</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000018" name="Process Creation - MavInject Process Injection" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[%2FINJECTRUNNING]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000018</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:t1055</tag>
      <tag origin="1">attack:process_injection</tag>
      <tag origin="1">attack:t1218</tag>
      <tag origin="1">attack:signed_binary_proxy_execution</tag>
    </rule>
    <rule>
      <id>47-6000019</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - MMC Spawning Windows Shell</message>
      <description>Detects a Windows command line executable started from MMC.</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000019" name="Process Creation - MMC Spawning Windows Shell" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="trigger_1" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" ordinal="1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388616">
        <filterData name="value" value="ParentName|6751494449278544611[mmc.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[bash.exe,bitsadmin.exe,cmd.exe,cscript.exe,powershell.exe,reg.exe,regsvr32.exe,sh.exe,wscript.exe]"/>
        <filterData name="operator" value="IN"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="trigger_1"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000019</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:lateral_movement</tag>
      <tag origin="1">attack:t1175</tag>
    </rule>
    <rule>
      <id>47-6000020</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Bitsadmin Download</message>
      <description>Detects usage of bitsadmin downloading a file
https://blog.netspi.com/15-ways-to-download-a-file/#bitsadmin
https://isc.sans.edu/diary/22264</description>
      <origin>1</origin>
      <severity>50</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000020" name="Process Creation - Bitsadmin Download" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[bitsadmin.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)%2Ftransfer]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000020</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:persistence</tag>
      <tag origin="1">attack:t1197</tag>
      <tag origin="1">attack:s0190</tag>
    </rule>
    <rule>
      <id>47-6000021</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - PowerShell Download from URL</message>
      <description>Detects a Powershell process that contains download commands in its command line string</description>
      <origin>1</origin>
      <severity>50</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000021" name="Process Creation - PowerShell Download from URL" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)new-object%20(system%5C.)%3Fnet%5C.webclient%5C)%5C.downloadfile%5C(,(%3Fi)new-object%20(system%5C.)%3Fnet%5C.webclient%5C)%5C.downloadstring%5C(]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[powershell.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000021</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:t1086</tag>
    </rule>
    <rule>
      <id>47-6000022</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - Renamed Powershell</message>
      <description>Detects copying and renaming of powershell.exe before execution (RETEFE malware DOC/macro starting Sept 2018)
https://twitter.com/christophetd/status/1164506034720952320</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000022" name="Sysmon - Renamed Powershell" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_4259873">
        <filterData name="value" value="Description|12622590293378144023[Windows%20PowerShell,Windows%20PowerShell%20ISE]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[powershell.exe,powershell_ise.exe]"/>
        <filterData name="operator" value="IN"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000022</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">car:2013-05-009</tag>
    </rule>
    <rule>
      <id>47-6000023</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - PsExec Service Start</message>
      <description>Detects a PsExec service start</description>
      <origin>1</origin>
      <severity>25</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000023" name="Process Creation - PsExec Service Start" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)psexec%5C.exe]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000023</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:t1035</tag>
      <tag origin="1">attack:s0029</tag>
    </rule>
    <rule>
      <id>47-6000024</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - WMI Spawning Windows PowerShell</message>
      <description>Detects WMI spawning PowerShell
https://github.com/Neo23x0/sigma/blob/master/rules/windows/process_creation/win_shell_spawn_susp_program.yml
https://any.run/report/68bc255f9b0db6a0d30a8f2dadfbee3256acfe12497bf93943bc1eab0735e45e/a2385d6f-34f7-403c-90d3-b1f9d2a90a5e</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000024" name="Process Creation - WMI Spawning Windows PowerShell" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388616">
        <filterData name="value" value="ParentName|6751494449278544611[WmiPrvSE.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[powershell.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000024</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:t1064</tag>
    </rule>
    <rule>
      <id>47-6000025</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - WMI Persistence - Script Event Consumer</message>
      <description>Detects WMI script event consumers
https://www.eideon.com/2018-03-02-THL03-WMIBackdoors/</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000025" name="Process Creation - WMI Persistence - Script Event Consumer" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454178">
        <filterData name="value" value="Image|12622590293378144023[C%3A%5CWINDOWS%5Csystem32%5Cwbem%5Cscrcons.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454177">
        <filterData name="value" value="ParentImage|12622590293378144023[C%3A%5CWindows%5CSystem32%5Csvchost.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000025</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:persistence</tag>
      <tag origin="1">attack:t1047</tag>
    </rule>
    <rule>
      <id>47-6000026</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Shells Spawned by Web Servers</message>
      <description>Particular web applications may spawn a shell process legitimately</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000026" name="Process Creation - Shells Spawned by Web Servers" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388616">
        <filterData name="value" value="ParentName|6751494449278544611[httpd.exe,nginx.exe,php-cgi.exe,w3wp.exe]"/>
        <filterData name="operator" value="IN"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[bash.exe,cmd.exe,powershell.exe,sh.exe]"/>
        <filterData name="operator" value="IN"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000026</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:persistence</tag>
      <tag origin="1">attack:privilege_escalation</tag>
      <tag origin="1">attack:t1100</tag>
    </rule>
    <rule>
      <id>47-6000027</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Suspicious Userinit Child Process</message>
      <description>Detects the creation of a process from Windows task manager
https://twitter.com/SBousseaden/status/1139811587760562176</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000027" name="Process Creation - Suspicious Userinit Child Process" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388616">
        <filterData name="value" value="ParentName|6751494449278544611[userinit.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[C%3A%5CWindows%5CSystem32%5Cexplorer.exe,C%3A%5CWindows%5CSystem32%5Cnetlogon.dll,C%3A%5CWindows%5CSysWOW64%5Cexplorer.exe,C%3A%5CWindows%5CSysWOW64%5Cnetlogon.dll]"/>
        <filterData name="operator" value="NOT_IN"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000027</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
    </rule>
    <rule>
      <id>47-6000028</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Quick Execution of a Series of Suspicious Commands</message>
      <description>Detects multiple suspicious process in a limited timeframe
https://car.mitre.org/wiki/CAR-2013-04-002</description>
      <origin>1</origin>
      <severity>25</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000028" name="Process Creation - Quick Execution of a Series of Suspicious Commands" eventType="event" correlationField="@4">
  <params/>
  <trigger name="trigger_1" root="true" count="1" timeout="300" timeUnit="SECOND" threshold="5"/>
  <rule name="rule_1" ordinal="1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[ARP.EXE,at.exe,attrib.exe,bcedit.exe,certutil.exe,cscript.exe,diskpart.exe,dsquery.exe,hostname.exe,icacls.exe,ipconfig.exe,mimikatz.exe,nbtstat.exe,net.exe,netsh.exe,nslookup.exe,PING.EXE,powershell.exe,psexec.exe,PSEXEC.EXE,quser.exe,qwinsta.exe,reg.exe,Robocopy.exe,runas.exe,sc.exe,schtasks.exe,ssh.exe,systeminfo.exe,taskkill.exe,telnet.exe,tracert.exe,vssadmin.exe,wbadmin.exe,wevtutil.exe,wscript.exe,xcopy.exe]"/>
        <filterData name="operator" value="IN"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="trigger_1"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000028</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">car:2013-04-002</tag>
    </rule>
    <rule>
      <id>47-6000029</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Scheduled Task Creation</message>
      <description>Detects the creation of scheduled tasks in user session</description>
      <origin>1</origin>
      <severity>25</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000029" name="Process Creation - Scheduled Task Creation" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[schtasks.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)%2Fcreate]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_7">
        <filterData name="value" value="UserIDSrc|6751494449278544611[SYSTEM]"/>
        <filterData name="operator" value="DOES_NOT_EQUAL"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000029</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:persistence</tag>
      <tag origin="1">attack:privilege_escalation</tag>
      <tag origin="1">attack:t1053</tag>
      <tag origin="1">attack:s0111</tag>
      <tag origin="1">car:2013-08-001</tag>
    </rule>
    <rule>
      <id>47-6000030</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Rubeus Hack Tool</message>
      <description>Detects command line parameters used by Rubeus hack tool
https://www.harmj0y.net/blog/redteaming/from-kekeo-to-rubeus/</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000030" name="Process Creation - Rubeus Hack Tool" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)%2Fimpersonateuser%3A,(%3Fi)asktgt%20%2Fuser%3A,(%3Fi)asreproast,(%3Fi)createnetonly%20%2Fprogram%3A,(%3Fi)dump%20%2Fservice%3Akrbtgt,(%3Fi)harvest%20%2Finterval%3A,(%3Fi)kerberoast,(%3Fi)ptt%20%2Fticket%3A,(%3Fi)renew%20%2Fticket%3A]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000030</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:t1003</tag>
      <tag origin="1">attack:credential_access</tag>
      <tag origin="1">attack:s0005</tag>
    </rule>
    <rule>
      <id>47-6000031</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Encoded IEX</message>
      <description>Detects a base64 encoded IEX command string in a process command line</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000031" name="Process Creation - Encoded IEX" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="trigger_1" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" ordinal="1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)IEX%20%5C((%5C%5B%7CNew)]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="rule_2" ordinal="2" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454179">
        <filterData name="value" value="ParentCommandLine|12622590293378144023[(%3Fi)IEX%20%5C((%5C%5B%7CNew)]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="trigger_1"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000031</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:t1086</tag>
      <tag origin="1">attack:t1140</tag>
    </rule>
    <rule>
      <id>47-6000032</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Executables Started in Suspicious Folder</message>
      <description>Detects process starts of binaries from a suspicious folder
https://github.com/mbevilacqua/appcompatprocessor/blob/master/AppCompatSearch.txt
https://www.secureworks.com/research/bronze-butler-targets-japanese-businesses
https://www.crowdstrike.com/resources/reports/2019-crowdstrike-global-threat-report/</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000032" name="Process Creation - Executables Started in Suspicious Folder" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454178">
        <filterData name="value" value="Image|12622590293378144023[%5CRSA%5CMachineKeys%5C,C%3A%5C%24Recycle.bin%5C,C%3A%5CIntel%5CLogs%5C,C%3A%5CPerfLogs%5C,C%3A%5CUsers%5CDefault%5C,C%3A%5CUsers%5CNetworkService%5C,C%3A%5CUsers%5CPublic%5C,C%3A%5CWindows%5Caddins%5C,C%3A%5CWindows%5CDebug%5C,C%3A%5CWindows%5CFonts%5C,C%3A%5CWindows%5CHelp%5C,C%3A%5CWindows%5CMedia%5C,C%3A%5CWindows%5Crepair%5C,C%3A%5CWindows%5Csecurity%5C,C%3A%5CWindows%5Csystem32%5Cconfig%5Csystemprofile%5C]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000032</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:t1036</tag>
    </rule>
    <rule>
      <id>47-6000033</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - WScript or CScript Dropper</message>
      <description>Detects wscript/cscript executions of scripts located in user directories</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000033" name="Process Creation - WScript or CScript Dropper" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[cscript.exe,wscript.exe]"/>
        <filterData name="operator" value="IN"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)C%3A%5C%5C(ProgramData%7CUsers)%5C%5C.*%5C.jse%3F,(%3Fi)C%3A%5C%5C(ProgramData%7CUsers)%5C%5C.*%5C.vb%5Baes%5D]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388616">
        <filterData name="value" value="ParentName|6751494449278544611[winzip.exe]"/>
        <filterData name="operator" value="DOES_NOT_EQUAL"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000033</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:t1064</tag>
    </rule>
    <rule>
      <id>47-6000034</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Possible Shim Database Persistence via sdbinst</message>
      <description>Detects installation of a new shim using sdbinst.exe. A shim can be used to load malicious DLLs into applications.
https://www.fireeye.com/blog/threat-research/2017/05/fin7-shim-databases-persistence.html</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000034" name="Process Creation - Possible Shim Database Persistence via sdbinst" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[sdbinst.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)%5C.sdb]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000034</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:persistence</tag>
      <tag origin="1">attack:t1138</tag>
    </rule>
    <rule>
      <id>47-6000036</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - MSHTA spwaned by SVCHOST as seen in LethalHTA</message>
      <description>Detects MSHTA.EXE spwaned by SVCHOST described in report
https://codewhitesec.blogspot.com/2018/07/lethalhta.html</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000036" name="Process Creation - MSHTA spwaned by SVCHOST as seen in LethalHTA" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388616">
        <filterData name="value" value="ParentName|6751494449278544611[svchost.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[mshta.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000036</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:t1070</tag>
    </rule>
    <rule>
      <id>47-6000037</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Terminal Service Process Spawn</message>
      <description>Detects a process spawned by the terminal service server process (this could be an indicator for an exploitation of CVE-2019-0708)
https://securingtomorrow.mcafee.com/other-blogs/mcafee-labs/rdp-stands-for-really-do-patch-understanding-the-wormable-rdp-vulnerability-cve-2019-0708/</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000037" name="Process Creation - Terminal Service Process Spawn" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454179">
        <filterData name="value" value="ParentCommandLine|12622590293378144023[(%3Fi)svchost%5C.exe.*termsvcs]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[rdpclip.exe]"/>
        <filterData name="operator" value="DOES_NOT_EQUAL"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000037</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">car:2013-07-002</tag>
    </rule>
    <rule>
      <id>47-6000038</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Suspicious RDP Redirect Using TSCON</message>
      <description>Detects a suspicious RDP session redirect using tscon.exe
http://www.korznikov.com/2017/03/0-day-or-feature-privilege-escalation.html
https://medium.com/@networksecurity/rdp-hijacking-how-to-hijack-rds-and-remoteapp-sessions-transparently-to-move-through-an-da2a1e73a5f6</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000038" name="Process Creation - Suspicious RDP Redirect Using TSCON" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)%2Fdest%3Ardp-tcp%3A]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000038</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:lateral_movement</tag>
      <tag origin="1">attack:privilege_escalation</tag>
      <tag origin="1">attack:t1076</tag>
      <tag origin="1">car:2013-07-002</tag>
    </rule>
    <rule>
      <id>47-6000039</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Suspicious Parent of Cscexe</message>
      <description>Detects a suspicious parent of csc.exe, which could by a sign of payload delivery
https://twitter.com/SBousseaden/status/1094924091256176641</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000039" name="Process Creation - Suspicious Parent of Cscexe" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[csc.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388616">
        <filterData name="value" value="ParentName|6751494449278544611[cscript.exe,mshta.exe,wscript.exe]"/>
        <filterData name="operator" value="IN"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000039</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:t1036</tag>
    </rule>
    <rule>
      <id>47-6000040</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Windows Shell Spawning Suspicious Program</message>
      <description>Detects a suspicious child process of a Windows shell
https://mgreen27.github.io/posts/2018/04/02/DownloadCradle.html</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000040" name="Process Creation - Windows Shell Spawning Suspicious Program" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388616">
        <filterData name="value" value="ParentName|6751494449278544611[cmd.exe,cscript.exe,mshta.exe,powershell.exe,rundll32.exe,wmiprvse.exe,wscript.exe]"/>
        <filterData name="operator" value="IN"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[bitsadmin.exe,certutil.exe,mshta.exe,nslookup.exe,schtasks.exe]"/>
        <filterData name="operator" value="IN"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000040</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:t1064</tag>
    </rule>
    <rule>
      <id>47-6000041</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - CobaltStrike Process Injection</message>
      <description>Detects usage of bitsadmin downloading a file</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000041" name="Sysmon - CobaltStrike Process Injection" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8650753">
        <filterData name="value" value="EventID|9887219683253088746[8]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454174">
        <filterData name="value" value="StartAddress|12622590293378144023[0B80]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000041</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:t1055</tag>
    </rule>
    <rule>
      <id>47-6000042</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - Executable in ADS</message>
      <description>Detects the creation of an ADS data stream that contains an executable (non-empty imphash)
https://twitter.com/0xrawsec/status/1002478725605273600?s=21</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000042" name="Sysmon - Executable in ADS" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8650753">
        <filterData name="value" value="EventID|9887219683253088746[15]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454175">
        <filterData name="value" value="Imphash|12622590293378144023[00000000000000000000000000000000]"/>
        <filterData name="operator" value="DOES_NOT_EQUAL"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000042</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:t1027</tag>
      <tag origin="1">attack:s0139</tag>
    </rule>
    <rule>
      <id>47-6000043</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - Default PowerSploit and Empire Schtasks Persistence</message>
      <description>Detects the creation of a schtask via PowerSploit or Empire Default Configuration.
https://github.com/0xdeadbeefJERKY/PowerSploit/blob/8690399ef70d2cad10213575ac67e8fa90ddf7c3/Persistence/Persistence.psm1
https://github.com/EmpireProject/Empire/blob/master/lib/modules/powershell/persistence/userland/schtasks.py
https://github.com/EmpireProject/Empire/blob/master/lib/modules/powershell/persistence/elevated/schtasks.py</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000043" name="Sysmon - Default PowerSploit and Empire Schtasks Persistence" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[powershell.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi).*schtasks.*%2FCreate.*%2FSC.*(ONLOGON%7CDAILY%7CONIDLE%7CUpdater).*%2FTN.*Updater.*%2FTR.*powershell.*]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000043</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:t1086</tag>
      <tag origin="1">attack:persistence</tag>
      <tag origin="1">attack:privilege_escalation</tag>
      <tag origin="1">attack:t1053</tag>
      <tag origin="1">attack:s0111</tag>
      <tag origin="1">attack:g0022</tag>
      <tag origin="1">attack:g0060</tag>
    </rule>
    <rule>
      <id>47-6000044</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - PsExec Detection</message>
      <description>Detects usage of PSEXEC.EXE</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000044" name="Sysmon - PsExec Detection" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="trigger_1" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" ordinal="1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_4259873">
        <filterData name="value" value="Description|12622590293378144023[Execute%20processes%20remotely]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="rule_2" ordinal="2" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388612">
        <filterData name="value" value="Product|6751494449278544611[Sysinternals%20PsExec]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="trigger_1"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000044</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
    </rule>
    <rule>
      <id>47-6000045</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - Suspicious File Characteristics due to Missing Fields</message>
      <description>Detects Executables without Description and Product likely created with py2exe - Modified from SIGMA
https://securelist.com/muddywater/88059/
https://www.virustotal.com/#/file/276a765a10f98cda1a38d3a31e7483585ca3722ecad19d784441293acf1b7beb/detection</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000045" name="Sysmon - Suspicious File Characteristics due to Missing Fields" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_4259873">
        <filterData name="value" value="Description|12622590293378144023[%3F]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388612">
        <filterData name="value" value="Product|6751494449278544611[%3F]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000045</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
    </rule>
    <rule>
      <id>47-6000047</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - CACTUSTORCH Remote Thread Creation</message>
      <description>Detects remote thread creation from CACTUSTORCH as described in references.
https://twitter.com/SBousseaden/status/1090588499517079552
https://github.com/mdsecactivebreach/CACTUSTORCH</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000047" name="Sysmon - CACTUSTORCH Remote Thread Creation" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8650753">
        <filterData name="value" value="EventID|9887219683253088746[8]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454177">
        <filterData name="value" value="ParentImage|12622590293378144023[%5CSystem32%5Ccscript.exe,%5CSystem32%5Cmshta.exe,%5CSystem32%5Cwscript.exe,EXCEL.EXE,WINWORD.EXE]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454178">
        <filterData name="value" value="Image|12622590293378144023[%5CSysWOW64%5C]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000047</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:t1055</tag>
      <tag origin="1">attack:t1064</tag>
    </rule>
    <rule>
      <id>47-6000048</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - DHCP Callout DLL installation</message>
      <description>Detects the installation of a Callout DLL via CalloutDlls and CalloutEnabled parameter in Registry, which can be used to execute code in context of the DHCP server (restart required)
https://blog.3or.de/mimilib-dhcp-server-callout-dll-injection.html
https://technet.microsoft.com/en-us/library/cc726884(v=ws.10).aspx
https://msdn.microsoft.com/de-de/library/windows/desktop/aa363389(v=vs.85).aspx</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000048" name="Sysmon - DHCP Callout DLL installation" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8650753">
        <filterData name="value" value="EventID|9887219683253088746[13]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_21364738">
        <filterData name="value" value="21364738[%5CServices%5CDHCPServer%5CParameters%5CCalloutDlls,%5CServices%5CDHCPServer%5CParameters%5CCalloutEnabled]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000048</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:t1112</tag>
      <tag origin="1">attack:t1073</tag>
    </rule>
    <rule>
      <id>47-6000049</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - DNS ServerLevelPluginDll Install</message>
      <description>Detects the installation of a plugin DLL via ServerLevelPluginDll parameter in Registry, which can be used to execute code in context of the DNS server (restart required)
https://medium.com/@esnesenon/feature-not-bug-dnsadmin-to-dc-compromise-in-one-line-a0f779b8dc83</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000049" name="Sysmon - DNS ServerLevelPluginDll Install" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="trigger_1" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" ordinal="1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8650753">
        <filterData name="value" value="EventID|9887219683253088746[13]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_21364738">
        <filterData name="value" value="21364738[%5Cservices%5CDNS%5CParameters%5CServerLevelPluginDll]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="rule_2" ordinal="2" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[dnscmd.exe%20%2Fconfig%20%2Fserverlevelplugindll]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="trigger_1"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000049</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:t1073</tag>
    </rule>
    <rule>
      <id>47-6000050</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - Detection of SafetyKatz</message>
      <description>Detects possible SafetyKatz Behaviour
https://github.com/GhostPack/SafetyKatz</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000050" name="Sysmon - Detection of SafetyKatz" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8650753">
        <filterData name="value" value="EventID|9887219683253088746[11]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_4259843">
        <filterData name="value" value="Filename|10814778825021535730[%5CTemp%5Cdebug.bin]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000050</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:t1003</tag>
      <tag origin="1">attack:credential_access</tag>
    </rule>
    <rule>
      <id>47-6000051</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - Logon Scripts UserInitMprLogonScript</message>
      <description>Detects creation or execution of UserInitMprLogonScript persistence method - MODIFIED
https://attack.mitre.org/techniques/T1037/
exec_exclusion:
     Image: '*\explorer.exe'
     CommandLine: '*\netlogon.bat'</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000051" name="Sysmon - Logon Scripts UserInitMprLogonScript" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="trigger_1" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" ordinal="1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[UserInitMprLogonScript]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="rule_2" ordinal="2" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8650753">
        <filterData name="value" value="EventID|9887219683253088746[1]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388616">
        <filterData name="value" value="ParentName|6751494449278544611[userinit.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[explorer.exe]"/>
        <filterData name="operator" value="DOES_NOT_EQUAL"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="trigger_1"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000051</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:t1037</tag>
      <tag origin="1">attack:lateral_movement</tag>
      <tag origin="1">attack:persistence</tag>
    </rule>
    <rule>
      <id>47-6000052</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - Suspicious Typical Malware Back Connect Ports</message>
      <description>Detects programs that connect to typical malware back connect ports based on statistical analysis from two different sandbox system databases - MODIFIED
https://docs.google.com/spreadsheets/d/17pSTDNpa0sf6pHeRhusvWG6rThciE8CsXTSlDUAZDyo</description>
      <origin>1</origin>
      <severity>50</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000052" name="Sysmon - Suspicious Typical Malware Back Connect Ports" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8650753">
        <filterData name="value" value="EventID|9887219683253088746[3]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="DEST_PORT">
        <filterData name="value" value="$watch=Command%20and%20Control%20Ports"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000052</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:command_and_control</tag>
      <tag origin="1">attack:t1043</tag>
    </rule>
    <rule>
      <id>47-6000053</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - Mimikatz through Windows Remote Management</message>
      <description>Detects usage of mimikatz through WinRM protocol by monitoring access to lsass process by wsmprovhost.exe.
https://pentestlab.blog/2018/05/15/lateral-movement-winrm/</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000053" name="Sysmon - Mimikatz through Windows Remote Management" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8650753">
        <filterData name="value" value="EventID|9887219683253088746[10]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000053</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:t1003</tag>
      <tag origin="1">attack:credential_access</tag>
      <tag origin="1">attack:t1028</tag>
      <tag origin="1">attack:s0005</tag>
    </rule>
    <rule>
      <id>47-6000054</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - Suspicious Debugger Registration Cmdline</message>
      <description>Detects the registration of a debugger for a program that is available in the logon screen (sticky key backdoor). 
https://blogs.technet.microsoft.com/jonathantrull/2016/10/03/detecting-sticky-key-backdoors/</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000054" name="Process Creation - Suspicious Debugger Registration Cmdline" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)%5C%5CCurrentVersion%5C%5CImage%20File%20Execution%20Options%5C%5C(sethc%7Cutilman%7Cosk%7Cmagnify%7Cnarrator%7Cdisplayswitch)%5C.exe]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000054</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:persistence</tag>
      <tag origin="1">attack:privilege_escalation</tag>
      <tag origin="1">attack:t1015</tag>
    </rule>
    <rule>
      <id>47-6000055</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Process Creation - MSHTA Spawning Windows Shell</message>
      <description>Detects a Windows command line executable started from MSHTA.
https://www.trustedsec.com/july-2015/malicious-htas/</description>
      <origin>1</origin>
      <severity>75</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000055" name="Process Creation - MSHTA Spawning Windows Shell" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388616">
        <filterData name="value" value="ParentName|6751494449278544611[mshta.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[bash.exe,bitsadmin.exe,cmd.exe,cscript.exe,powershell.exe,reg.exe,regsvr32.exe,sh%2Cexe,wscript.exe]"/>
        <filterData name="operator" value="IN"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000055</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:t1170</tag>
      <tag origin="1">car:2013-02-003</tag>
      <tag origin="1">car:2013-03-001</tag>
    </rule>
    <rule>
      <id>47-6000056</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - Control Panel Items</message>
      <description>Detects the use of a control panel item (.cpl) outside of the System32 folder
https://attack.mitre.org/techniques/T1196/</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000056" name="Sysmon - Control Panel Items" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)%5C.cpl]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[$watch=Control%20Panel%20Items]"/>
        <filterData name="operator" value="DOES_NOT_EQUAL"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000056</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:execution</tag>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:t1196</tag>
    </rule>
    <rule>
      <id>47-6000057</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - Security Support Provider SSP added to LSA configuration</message>
      <description>Detects the addition of a SSP to the registry. Upon a reboot or API call, SSP DLLs gain access to encrypted and plaintext passwords stored in Windows.
https://attack.mitre.org/techniques/T1101/
https://powersploit.readthedocs.io/en/latest/Persistence/Install-SSP/</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000057" name="Sysmon - Security Support Provider SSP added to LSA configuration" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8650753">
        <filterData name="value" value="EventID|9887219683253088746[13]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_21364738">
        <filterData name="value" value="21364738[HKLM%5CSystem%5CCurrentControlSet%5CControl%5CLsa%5COSConfig%5CSecurity%20Packages,HKLM%5CSystem%5CCurrentControlSet%5CControl%5CLsa%5CSecurity%20Packages]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454178">
        <filterData name="value" value="Image|12622590293378144023[C%3A%5CWindows%5CSystem32%5Cmsiexec.exe,C%3A%5CWindows%5CSysWOW64%5Cmsiexec.exe]"/>
        <filterData name="operator" value="NOT_IN"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000057</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:persistence</tag>
      <tag origin="1">attack:t1011</tag>
    </rule>
    <rule>
      <id>47-6000058</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - Sticky Key Like Backdoor Usage</message>
      <description>Detects the usage and installation of a backdoor that uses an option to register a malicious debugger for built-in tools that are accessible in the login screen
https://blogs.technet.microsoft.com/jonathantrull/2016/10/03/detecting-sticky-key-backdoors/</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000058" name="Sysmon - Sticky Key Like Backdoor Usage" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="trigger_1" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" ordinal="1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8650753">
        <filterData name="value" value="EventID|9887219683253088746[13]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454178">
        <filterData name="value" value="Image|12622590293378144023[%5CSOFTWARE%5CMicrosoft%5CWindows%20NT%5CCurrentVersion%5CImage%20File%20Execution%20Options%5CDisplaySwitch.exe%5CDebugger,%5CSOFTWARE%5CMicrosoft%5CWindows%20NT%5CCurrentVersion%5CImage%20File%20Execution%20Options%5CMagnify.exe%5CDebugger,%5CSOFTWARE%5CMicrosoft%5CWindows%20NT%5CCurrentVersion%5CImage%20File%20Execution%20Options%5CNarrator.exe%5CDebugger,%5CSOFTWARE%5CMicrosoft%5CWindows%20NT%5CCurrentVersion%5CImage%20File%20Execution%20Options%5Cosk.exe%5CDebugger,%5CSOFTWARE%5CMicrosoft%5CWindows%20NT%5CCurrentVersion%5CImage%20File%20Execution%20Options%5Csethc.exe%5CDebugger,%5CSOFTWARE%5CMicrosoft%5CWindows%20NT%5CCurrentVersion%5CImage%20File%20Execution%20Options%5Cutilman.exe%5CDebugger]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388617">
        <filterData name="value" value="EventType|6751494449278544611[SetValue]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="rule_2" ordinal="2" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8388616">
        <filterData name="value" value="ParentName|6751494449278544611[winlogon.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)cmd%5C.exe%20(sethc%7Cutilman%7Cosk%7CMagnify%7CNarrator%7CDisplaySwitch)%5C.exe]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="trigger_1"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000058</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:persistence</tag>
      <tag origin="1">attack:privilege_escalation</tag>
      <tag origin="1">attack:t1015</tag>
      <tag origin="1">car:2014-11-003</tag>
      <tag origin="1">car:2014-11-008</tag>
    </rule>
    <rule>
      <id>47-6000059</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - UAC Bypass via Event Viewer</message>
      <description>Detects UAC bypass method using Windows event viewer
https://enigma0x3.net/2016/08/15/fileless-uac-bypass-using-eventvwr-exe-and-registry-hijacking/
https://www.hybrid-analysis.com/sample/e122bc8bf291f15cab182a5d2d27b8db1e7019e4e96bb5cdbd1dfe7446f3f51f?environmentId=100</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000059" name="Sysmon - UAC Bypass via Event Viewer" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="trigger_1" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" ordinal="1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8650753">
        <filterData name="value" value="EventID|9887219683253088746[13]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_21364738">
        <filterData name="value" value="21364738[%5Cmscfile%5Cshell%5Copen%5Ccommand]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="rule_2" ordinal="2" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="trigger_1"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8650753">
        <filterData name="value" value="EventID|9887219683253088746[1]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388616">
        <filterData name="value" value="ParentName|6751494449278544611[eventvwr.exe]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388615">
        <filterData name="value" value="ImageName|6751494449278544611[mmc.exe]"/>
        <filterData name="operator" value="DOES_NOT_EQUAL"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="trigger_1"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000059</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:privilege_escalation</tag>
      <tag origin="1">attack:t1088</tag>
      <tag origin="1">car:2019-04-001</tag>
    </rule>
    <rule>
      <id>47-6000060</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Sysmon - Registry Persistence Mechanisms</message>
      <description>Detects persistence registry keys
https://oddvar.moe/2018/04/10/persistence-using-globalflags-in-image-file-execution-options-hidden-from-autoruns-exe/</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000060" name="Sysmon - Registry Persistence Mechanisms" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8650753">
        <filterData name="value" value="EventID|9887219683253088746[13]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454178">
        <filterData name="value" value="Image|12622590293378144023[(%3Fi)%5C%5CSOFTWARE%5C%5CMicrosoft%5C%5CWindows%20NT%5C%5CCurrentVersion%5C%5CImage%20File%20Execution%20Options%5C%5C.*%5C%5CGlobalFlag,(%3Fi)%5C%5CSOFTWARE%5C%5CMicrosoft%5C%5CWindows%20NT%5C%5CCurrentVersion%5C%5CSilentProcessExit%5C%5C.*%5C%5C(MonitorProcess%7CReportingMode)]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8388617">
        <filterData name="value" value="EventType|6751494449278544611[SetValue]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000060</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:persistence</tag>
      <tag origin="1">attack:privilege_escalation</tag>
      <tag origin="1">attack:t1183</tag>
      <tag origin="1">car:2013-01-002</tag>
    </rule>
    <rule>
      <id>47-6000061</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Built-In - Mimikatz Use</message>
      <description>This method detects mimikatz keywords in different Eventlogs (some of them only appear in older Mimikatz version that are however still used by different threat groups) --MODIFIED</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000061" name="Built-In - Mimikatz Use" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8454170">
        <filterData name="value" value="CommandLine|12622590293378144023[(%3Fi)%3C3%20eo%5C.oe,(%3Fi)lsadump%3A%3Asam,(%3Fi)mimikatz,(%3Fi)mimilib,(%3Fi)privilege%3A%3Adebug,(%3Fi)sekurlsa%3A%3Alogonpasswords]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000061</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:t1003</tag>
      <tag origin="1">attack:credential_access</tag>
      <tag origin="1">attack:lateral_movement</tag>
      <tag origin="1">attack:s0002</tag>
      <tag origin="1">car:2019-04-004</tag>
      <tag origin="1">car:2013-07-001</tag>
    </rule>
    <rule>
      <id>47-6000062</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Built-In - Scanner PoC for CVE-2019-0708 RDP RCE vuln</message>
      <description>Detects the use of a scanner by zerosum0x0 that discovers targets vulnerable to  CVE-2019-0708 RDP RCE aka BlueKeep
https://twitter.com/AdamTheAnalyst/status/1134394070045003776
https://github.com/zerosum0x0/CVE-2019-0708</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000062" name="Built-In - Scanner PoC for CVE-2019-0708 RDP RCE vuln" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_7">
        <filterData name="value" value="UserIDSrc|6751494449278544611[AAAAAAA]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000062</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:lateral_movement</tag>
      <tag origin="1">attack:t1210</tag>
      <tag origin="1">car:2013-07-002</tag>
    </rule>
    <rule>
      <id>47-6000063</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Built-In - NetNTLM Downgrade Attack</message>
      <description>Detects post exploitation using NetNTLM downgrade attacks
https://www.optiv.com/blog/post-exploitation-using-netntlm-downgrade-attacks</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000063" name="Built-In - NetNTLM Downgrade Attack" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8650753">
        <filterData name="value" value="EventID|9887219683253088746[13]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_8454178">
        <filterData name="value" value="Image|12622590293378144023[(%3Fi)SYSTEM%5C%5C%5C%5C.*ControlSet.*%5C%5CControl%5C%5CLsa%5C%5Clmcompatibilitylevel,(%3Fi)SYSTEM%5C%5C%5C%5C.*ControlSet.*%5C%5CControl%5C%5CLsa%5C%5CNtlmMinClientSec,(%3Fi)SYSTEM%5C%5C%5C%5C.*ControlSet.*%5C%5CControl%5C%5CLsa%5C%5CRestrictSendingNTLMTraffic]"/>
        <filterData name="operator" value="REGEX"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000063</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:credential_access</tag>
      <tag origin="1">attack:t1212</tag>
    </rule>
    <rule>
      <id>47-6000064</id>
      <normid>4026531840</normid>
      <revision>38144</revision>
      <sid>0</sid>
      <class>0</class>
      <message>Built-In - DHCP Server Loaded the CallOut DLL</message>
      <description>This rule detects a DHCP server in which a specified Callout DLL (in registry) was loaded
https://blog.3or.de/mimilib-dhcp-server-callout-dll-injection.html
https://technet.microsoft.com/en-us/library/cc726884(v=ws.10).aspx
https://msdn.microsoft.com/de-de/library/windows/desktop/aa363389(v=vs.85).aspx</description>
      <origin>1</origin>
      <severity>100</severity>
      <type>13</type>
      <action>255</action>
      <action_initial>255</action_initial>
      <action_disallowed>0</action_disallowed>
      <other_bits_default>4</other_bits_default>
      <other_bits_disallowed>0</other_bits_disallowed>
      <text><![CDATA[<ruleset id="47-6000064" name="Built-In - DHCP Server Loaded the CallOut DLL" eventType="event" correlationField="NONE">
  <params/>
  <trigger name="Root Trigger" root="true" count="1" timeout="600" timeUnit="SECOND" threshold="1"/>
  <rule name="rule_1" eventType="event">
    <activate type="EVENT"/>
    <match count="1" matchType="FILTER"/>
    <action type="TRIGGER" trigger="Root Trigger"/>
    <matchFilter type="and">
      <singleFilterComponent type="CUST_8650753">
        <filterData name="value" value="EventID|9887219683253088746[13]"/>
        <filterData name="operator" value="EQUALS"/>
      </singleFilterComponent>
      <singleFilterComponent type="CUST_21364738">
        <filterData name="value" value="21364738[%5CREGISTRY%5CMACHINE%5CSYSTEM%5CControlSet001%5CServices%5CDHCPServer%5CParameters%5CCalloutDlls,%5CREGISTRY%5CMACHINE%5CSYSTEM%5CControlSet001%5CServices%5CDHCPServer%5CParameters%5CCalloutEnabled]"/>
        <filterData name="operator" value="CONTAINS"/>
      </singleFilterComponent>
    </matchFilter>
  </rule>
  <rule name="Root Rule">
    <activate type="TRIGGER" triggerName="Root Trigger"/>
    <match count="0" matchType="FILTER"/>
    <action type="COMPLETE_ACTION"/>
  </rule>
  <property>
    <name>sigid</name>
    <value>6000064</value>
  </property>
  <property>
    <name>rev</name>
    <value>9.5.0</value>
  </property>
  <property>
    <name>user</name>
    <value>1</value>
  </property>
  <property>
    <name>forbid</name>
    <value>F</value>
  </property>
</ruleset>
]]></text>
      <tag origin="1">attack:defense_evasion</tag>
      <tag origin="1">attack:t1073</tag>
    </rule>
  </rules>
  <variables count="0"/>
  <policies count="1" export_mode="0">
    <policy>
      <name>Rule Correlation</name>
      <uid>6737807874650967430</uid>
      <alerts_only>2</alerts_only>
      <exceptions_var count="0"/>
      <exceptions_preprocess count="0"/>
      <exceptions_rule count="0"/>
    </policy>
  </policies>
</nitro_policy>
